/*
 * Globalize Culture cs-CZ
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

export default (function( window, undefined ) {

    var Globalize;

    if ( typeof require !== "undefined"
        && typeof exports !== "undefined"
        && typeof module !== "undefined" ) {
        // Assume CommonJS
        Globalize = require( "globalize" );
    } else {
        // Global variable
        Globalize = window.Globalize;
    }

    Globalize.addCultureInfo( "cs-CZ", "default", {
        name: "cs-CZ",
        englishName: "Czech (Czech Republic)",
        nativeName: "ÄŤeĹˇtina (ÄŚeskĂˇÂ republika)",
        language: "cs",
        numberFormat: {
            ",": "Â ",
            ".": ",",
            NaN: "NenĂ­ ÄŤĂ­slo",
            negativeInfinity: "-nekoneÄŤno",
            positiveInfinity: "+nekoneÄŤno",
            percent: {
                pattern: ["-n%","n%"],
                ",": "Â ",
                ".": ","
            },
            currency: {
                pattern: ["-n $","n $"],
                ",": "Â ",
                ".": ",",
                symbol: "KÄŤ"
            }
        },
        calendars: {
            standard: {
                "/": ".",
                firstDay: 1,
                days: {
                    names: ["nedÄ›le","pondÄ›lĂ­","ĂşterĂ˝","stĹ™eda","ÄŤtvrtek","pĂˇtek","sobota"],
                    namesAbbr: ["ne","po","Ăşt","st","ÄŤt","pĂˇ","so"],
                    namesShort: ["ne","po","Ăşt","st","ÄŤt","pĂˇ","so"]
                },
                months: {
                    names: ["leden","Ăşnor","bĹ™ezen","duben","kvÄ›ten","ÄŤerven","ÄŤervenec","srpen","zĂˇĹ™Ă­","Ĺ™Ă­jen","listopad","prosinec",""],
                    namesAbbr: ["1","2","3","4","5","6","7","8","9","10","11","12",""]
                },
                monthsGenitive: {
                    names: ["ledna","Ăşnora","bĹ™ezna","dubna","kvÄ›tna","ÄŤervna","ÄŤervence","srpna","zĂˇĹ™Ă­","Ĺ™Ă­jna","listopadu","prosince",""],
                    namesAbbr: ["1","2","3","4","5","6","7","8","9","10","11","12",""]
                },
                AM: ["dop.","dop.","DOP."],
                PM: ["odp.","odp.","ODP."],
                eras: [{"name":"n. l.","start":null,"offset":0}],
                patterns: {
                    d: "d.M.yyyy",
                    D: "d. MMMM yyyy",
                    t: "H:mm",
                    T: "H:mm:ss",
                    f: "d. MMMM yyyy H:mm",
                    F: "d. MMMM yyyy H:mm:ss",
                    M: "dd MMMM",
                    Y: "MMMM yyyy"
                }
            }
        }
    });

}( this ));

